version: '3.8'
services:
  app:
    container_name: simple-calculator
    image: test-java-spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod